services:
  postgres:
    image: postgres:18
    container_name: kalshi-sports-copilot-db
    environment:
      POSTGRES_DB: kalshi_sports_copilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - kalshi_sports_copilot_pgdata_v18_cluster:/var/lib/postgresql

volumes:
  kalshi_sports_copilot_pgdata_v18_cluster:
